USE DataWarehouseAnalytics;
GO
/*DATA EXPLORATION */
-- EXPLORE ALL OBJECTS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES

-- EXPLORE ALL COLUMNS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- EXPLORE ALL COUNTRIES OUR CUSYOMERS COME FROM.
SELECT DISTINCT country FROM gold.dim_customers

-- EXPLORE ALL CATEGORIES "THE MAJOR DIVISIONS"
SELECT DISTINCT category, subcategory,product_name 
FROM gold.dim_products
ORDER BY 1,2,3

-- FIND THE DATE OF THE FIRST AND LAST ORDER
SELECT 
MIN(order_date) AS first_order_date,
MAX(order_date) AS last_order_date,
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS order_range_years,
DATEDIFF(MONTH,MIN(order_date),MAX(order_date)) AS order_range_months
FROM gold.fact_sales

-- FIND THE YOUNGEST AND THE OLDEST CUSTOMER
SELECT
MAX(birthdate) AS youngest_birthdate,
DATEDIFF(YEAR,MAX(birthdate),GETDATE()) AS youngest_customer_age,
MIN(birthdate) AS oldest_birthdate,
DATEDIFF(YEAR,MIN(birthdate),GETDATE()) AS oldest_customer_age
FROM gold.dim_customers
/*MEASURES EXPLORATION */
--FIND THE TOTAL SALES
SELECT 
SUM(sales_amount) AS total_sales
FROM gold.fact_sales

--FIND HOW MANY ITEMS ARE SOLD
SELECT 
SUM(quantity) AS total_quantity
FROM gold.fact_sales

--FIND THE AVG SELLING PRICE
SELECT 
AVG(price) AS avg_price
FROM gold.fact_sales

--FIND THE TOTAL NUMBER OF ORDERS
SELECT 
COUNT(Order_Number) AS total_orders
FROM gold.fact_sales
SELECT 
COUNT(DISTINCT(Order_Number)) AS total_orders
FROM gold.fact_sales

--FIND THE TOTAL NUMBER OF PRODUCTS
SELECT 
COUNT(Product_Name) AS total_products
FROM gold.dim_products
SELECT 
COUNT(DISTINCT(Product_Name)) AS total_products
FROM gold.dim_products

--FIND THE TOTAL NUMBER OF CUSTOMERS
SELECT 
COUNT(customer_key) AS total_customers
FROM gold.dim_customers
SELECT 
COUNT(DISTINCT(customer_key)) AS total_customers
FROM gold.dim_customers

--FIND THE TOTAL NUMBER OF CUSTOMERS THAT HAS PLACED AN ORDER
SELECT 
COUNT(customer_key) AS total_customers
FROM gold.fact_sales
SELECT
COUNT(DISTINCT(customer_key)) AS total_customers
FROM gold.fact_sales

/*GENERATE A REPORT THAT SHOWS ALL KEYS METERIC OF THE BUSINESS */
SELECT 'Total Sales' AS measure_name, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity',SUM(quantity) AS total_quantity FROM gold.fact_sales
UNION ALL
SELECT 'Average Price',AVG(price) AS avg_price FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Orders', COUNT(DISTINCT(Order_Number)) AS total_orders FROM gold.fact_sales
UNION ALL
SELECT 'Total No. Products', COUNT(DISTINCT(Product_Name)) AS total_products FROM gold.dim_products
UNION ALL
SELECT 'Total No. Customers', COUNT(DISTINCT(customer_key)) AS total_customers FROM gold.dim_customers

/* MAGNITUDE ANALYSIS */
-- FIND TOTAL CUSTOMERS BY COUNTRIES
SELECT
country,
COUNT(customer_key)AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

-- FIND TOTAL CUSTOMERS BY GENDER
SELECT
gender,
COUNT(customer_key)AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC
-- FIND TOTAL PRODUCTS BY CATEGORY
SELECT
category,
COUNT(product_key)AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

-- WHAT IS THE AVERAGE COSTS IN EACH CATEGORY?
SELECT
category,
AVG(Cost)AS avg_costs
FROM gold.dim_products
GROUP BY category
ORDER BY avg_costs DESC

-- WHAT IS THE TOTAL REVENUE GENERATED FOR EACH CATEGORY?
SELECT
p.category,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales f
LEFT JOIN gold.dim_products p
ON p.Product_key = f.product_key
GROUP BY p.category
ORDER BY total_revenue DESC

-- FIND TOTAL REVENUE IS GENERATED BY EACH CUSTOMER
SELECT 
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES
SELECT 
c.country,
SUM(f.Quantity) AS total_sold_items
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY
c.country
ORDER BY total_sold_items DESC

/* RANKING ANALYSIS */
-- WHICH 5 PRODUCTS GENERATE THE HIGHEST REVENUE?
SELECT TOP 5
p.Product_Name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key = f.Product_Key
GROUP BY p.Product_Name
ORDER BY total_revenue DESC

SELECT *
FROM(
	SELECT TOP 5
	p.Product_Name,
	SUM(f.sales_amount) AS total_revenue,
	RANK() OVER(ORDER BY SUM(f.sales_amount) DESC) AS rank_products
	FROM gold.fact_sales AS f
	LEFT JOIN gold.dim_products AS p
	ON p.product_key = f.Product_Key
	GROUP BY p.Product_Name
	ORDER BY total_revenue DESC)t

-- WHAT ARE THE 5 WORST-PERFORMING PRODUCTS IN TERMS OF SALES?
SELECT TOP 5
p.Product_Name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_products AS p
ON p.product_key = f.Product_Key
GROUP BY p.Product_Name
ORDER BY total_revenue ASC

-- FIND THE TOP 10 CUSTOMERS WHO HAVE GENERATED THE HIGHEST REVENUE
SELECT TOP 10
c.customer_key,
c.first_name,
c.last_name,
SUM(f.sales_amount) AS total_revenue
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_revenue DESC

-- THE 3 CUSTOMERS WITH THE FEWEST ORDERS PLACED

SELECT TOP 3
c.customer_key,
c.first_name,
c.last_name,
COUNT(DISTINCT Order_Number) AS total_orders
FROM gold.fact_sales AS f
LEFT JOIN gold.dim_customers AS c
ON c.customer_key = f.customer_key
GROUP BY
c.customer_key,
c.first_name,
c.last_name
ORDER BY total_orders DESC